// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import NavMenu from "./postDashboard/components/nav";
import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Social Media App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="mainDashboard bg-gray-800 flex flex-col ">
                    <div className="nav w-100% h-16 bg-orange-400 row-span-1">
                        <NavMenu />
                    </div>
                    <div className="content  row-span-11">
                        <div>{children}</div>
                    </div>
                </div>
            </body>
        </html>
    );
}
